### ISSUE TITLE
我在使用FROM查询时发现找不到Mapper

### ISSUE THREAD

**Issue by dinghung** [michaelliao/warpdb#3]
<img width="1199" alt="1" src="https://user-images.githubusercontent.com/6938390/105227596-7ae84400-5b9c-11eb-8e0d-d5bd67ac9b45.png">

**Comment by dinghung** [comment]
<img width="1199" alt="1" src="https://user-images.githubusercontent.com/6938390/105227758-a79c5b80-5b9c-11eb-9c25-2b4ac7d60900.png">

**Comment by dinghung** [comment]
环境：jdk11 mac idea

**Comment by dinghung** [comment]
<img width="1248" alt="2" src="https://user-images.githubusercontent.com/6938390/105231550-07e1cc00-5ba2-11eb-9564-06373f2f2500.png">

**Comment by dinghung** [comment]
OmUser方法没有从写hashCode

**Comment by michaelliao** [comment]
你用了多个ClassLoader加载了多个OmUser class

**Comment by dinghung** [comment]
> 你用了多个ClassLoader加载了多个OmUser class
确实是这个问题，由于是本地开发环境，启用了spring-boot-devtools，去掉就好了~ 谢谢！
