### ISSUE TITLE
Bean属性设置setter和getter时，会报错：Duplicate property name found: xx in class: xxx

### ISSUE THREAD

**Issue by jerrydotlam** [michaelliao/warpdb#5]
如上，如果一个pojo对象的属性加了@Column，然后又同时给这个属性生成setter和getter，在初始化时会报以上错误。

调试了代码，在getPropertiesIncludeHierarchy时会将有设置@Column的属性加入表，然后再判断该属性如果有getter方法，会再加入一次，导致重复。

不清楚廖老师是不是故意这么设计，建议大家属性直接设置为public而不用setter和getter

**Comment by michaelliao** [comment]
如果有getter需要把所有注解如@Column加到getter上

没有getter就把注解加到字段

**Comment by jerrydotlam** [comment]
> 如果有getter需要把所有注解如@column加到getter上
> 
> 没有getter就把注解加到字段

getter是用lombok生成的，有什么好办法没。

**Comment by michaelliao** [comment]
稍等30分钟
